# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[package]
version = "3.1.0"
title = "CAE Extension Bundle"
description = "Bundle of all CAE extensions, dependencies, and settings for Kit-CAE applications"
category = "CAE"
keywords = ["cae", "bundle"]

changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]

# Kit SDK dependencies beyond the base editor
"omni.kit.widget.layers" = {}           # Layer widget
"omni.kit.window.extensions" = {}       # Extensions window
"omni.anim.window.timeline" = {}        # Timeline widget
"omni.kit.window.script_editor" = {}    # Script editor
"omni.kit.window.usd_paths" = {}        # USD paths editor
"omni.kit.window.movie_capture" = {}    # Movie capture window
"omni.videoencoding" = {}               # Video encoding (mp4 support)
"omni.kit.property.layer" = {}			# Layer property editor

# Kit-CAE extensions
"omni.cae.schema" = {order = -100}      # all USD schemas should be loaded with order = -100
"omni.cae.usd_plugins" = { order = -100 } # all USD plugins should be loaded with order = -100
"omni.cae.core" = {}

# CAE Viz
"omni.cae.viz" = {}
"omni.cae.usd_plugins_importers" = {}

# UI
"omni.cae.context_menu" = {}
"omni.cae.property.bundle" = {}
"omni.cae.widget.stage_icons" = {}

# Testing
"omni.cae.testing" = {}

# Utility
"omni.cae.exVars" = {}
"omni.cae.startup" = {}

[[python.module]]
name = "omni.cae.bundle"

[[python.module]]
name = "omni.cae.scripts"

[settings]
# Allow specified resolution to dictate.
app.viewport.defaults.fillViewport = false

# disable DLSS
rtx-transient.dlssg.enabled = false

# Extend the options to add "Add MDL File" option.
exts."omni.kit.material.library".ui_show_list = ["OmniPBR", "OmniGlass", "OmniSurface", "USD Preview Surface", "Add MDL File"]

# IndeX specific settings.
rtx.index.overrideSubdivisionMode = "kd_tree"
rtx.index.overrideSubdivisionPartCount = 1
rtx.index.compositeEnabled = 1

# Flow specific settings: these are critical.
exts."omni.flowusd".voxelize_velocity_vec4 = false
exts."omni.flowusd".voxelize_velocity_float = true

# Streamline/Flow disocclusion settings: improves rendering when simulations
# use 1m per unit. These settings may be removed once the renderer handles this
# natively.
rtx.occlusionDetection.enabled = true
rtx.aovConverter.disocclusionScale = 2000000
rtx.disocclusionDetection.conservativeSurfaceDetection = false
rtx.disocclusionDetection.depthThreshold = 0.1
rtx.post.dlss.execMode = 1


[settings.persistent]
app.viewport.Viewport.Viewport0.resolution.0 = 1920
app.viewport.Viewport.Viewport0.resolution.1 = 1080

[documentation]
pages = [
    "docs/README.md",
    "docs/CHANGELOG.md",
]

[[test]]
name = "startup"

[[test]]
timeout = 900
args = [
    "--/exts/omni.kit.viewport.ready/activity_progress/enabled=false",
    "--/exts/omni.kit.viewport.ready/background_color=4289506321",
    "--/app/window/width=512",
    "--/app/window/height=512",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
]
