# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

[core]
# IndeX components are not reloadable
reloadable = false

[package]
version = "1.1.0"
title = "CAE IndeX"
description = "Extension providing IndeX Python bindings and generic Python-based importers and compute tasks."
category = "CAE"
readme  = "docs/README.md"
keywords = ["kit", "cae"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"

[dependencies]
"omni.rtx.index_composite" = {}
"omni.usd" = {}
"omni.usd.core" = {}

[[python.module]]
name = "omni.cae.index"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
cpp_api = [
]
